#!/usr/bin/env bash

## install node
./nave usemain "${NODE_VERSION:-stable}" || exit ${ERROR}

## ensure node/npm work
npm -v  > /dev/null 2>&1 || exit ${ERROR}
node -v > /dev/null 2>&1 || exit ${ERROR}

exit $?

